### ISSUE TITLE
项目下没 `.dockerenv` 文件

### ISSUE THREAD

**Issue by luojiyin1987** [gzyunke/test-docker#1]
根据 app.js  下的代码
```js
let isDocker = false;
try{
	fs.accessSync('/.dockerenv');
	isDocker = true;
	logger.info('run in docker')
}
``` 
我猜是根据是否有`.dockerenv` 文件，来判断是否在docker 环境运行

在 `docker-compose.yml`  文件下 没 mongo 相关配置

初学者 很难发现里面的问题

**Comment by gzyunke** [comment]
这个文件是容器里面根目录会有的，不需要项目目录有，只要是在docker容器中跑就会有这个文件，所以用这个来判断是否在容器里运行。
