### ISSUE TITLE
wsl版本问题

### ISSUE THREAD

**Issue by bogeyixiu** [gzyunke/test-docker#2]
老师您好，我按照您文档上的操作进行时，version怎么重复设置都是1，该怎么办呢？
![image](https://github.com/gzyunke/test-docker/assets/96643049/bfafad6c-5339-4317-b73f-1a4f1c628500)

**Comment by gzyunke** [comment]
你需要升级以下wsl，安装下新版本，去网上找下

**Comment by bogeyixiu** [comment]
好的，感谢☺
