### ISSUE TITLE
报错： Docker 客户端无法成功与 Docker 引擎通信，可能是由于 API 版本不匹配引起的

### ISSUE THREAD

**Issue by y2000zhang** [gzyunke/test-docker#3]
在powershell中运行 wsl.exe --list --verbose，显示docker-desktop在Running，但运行docker run -d -p 6379:6379 --name redis redis:latest命令报错：docker: request returned Internal Server Error for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create?name=redis, check if the server supports the requested API version.
See 'docker run --help'，这个报错的意思似乎是说“ Docker 客户端无法成功与 Docker 引擎通信，可能是由于 API 版本不匹配引起的”，重装了docker-desktop多次了，还是这样报错，不知道该怎么办了。

下面是powershell中运行的信息：
PS C:\WINDOWS\system32> wsl.exe --list --verbose
  NAME                   STATE           VERSION
* Ubuntu-22.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
  Ubuntu                 Stopped         2

PS C:\WINDOWS\system32> docker run -d -p 6379:6379 --name redis redis:latest
docker: request returned Internal Server Error for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create?name=redis, check if the server supports the requested API version.
See 'docker run --help'.

**Comment by gzyunke** [comment]
这个问题没遇到过，用 windws11 可能会问题少点
