### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by welthy** [gzyunke/test-docker#5]
docker run --rm hello-world或者docker network ls时都会报网络连接错误：
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect
按照搜索的解决方案
DockerCli -SwitchDaemon后也执行失败：
switching to windows engine: Post "http://ipc/engine/switch": open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.

不知道咋解决了，啥原因都不晓得。。。 求大佬教

**Comment by ChangXinze** [comment]
以管理员权限，运行cmd试试
