### ISSUE TITLE
UP你好，请问我在使用Android-docker时出现了问题可以帮助我解决吗

### ISSUE THREAD

**Issue by biggestspark** [gzyunke/test-docker#9]
![noVNC 和另外 35 个页面 - 个人 - Microsoft​ Edge 2024_7_5 21_59_52](https://github.com/gzyunke/test-docker/assets/144524980/ab0da4eb-8109-4722-a1d1-f58fde93f362)
![Containers - Docker Desktop 2024_7_5 22_02_07](https://github.com/gzyunke/test-docker/assets/144524980/e141a571-36f5-4d4b-8bd5-97789a8b8271)
错误大致是这两个，我用了GPT和油管都没有找到解决方案
希望您可以帮助我
蟹蟹！

**Comment by gzyunke** [comment]
这个不懂
